import { apiRequest, getJson, sendJson } from './apiClient'

export const getProjects = () => getJson('/projects')
export const getProject = (id) => getJson(`/projects/${id}`)
export const getProjectDetail = (id) => getJson(`/projects/${id}/detail`)
export const createProject = (payload) => sendJson('/projects', 'POST', payload)
export const updateProject = (id, payload) => sendJson(`/projects/${id}`, 'PUT', payload)
export const previewProjectImport = (rows) => sendJson('/projects/import/preview', 'POST', { rows })
export const importProjects = (rows) => sendJson('/projects/import', 'POST', { rows })
export const getCases = (params = '') => getJson(`/cases${params}`)
export const getCase = (id) => getJson(`/cases/${id}`)
export const createCase = (payload) => sendJson('/cases', 'POST', payload)
export const updateCase = (id, payload) => sendJson(`/cases/${id}`, 'PUT', payload)
export const getAlerts = (params = '') => getJson(`/alerts${params}`)
export const acknowledgeAlert = (id) => sendJson(`/alerts/${id}/acknowledge`, 'PUT', {})
export const getRecommendations = (params = '') => getJson(`/recommendations${params}`)
export const updateRecommendation = (id, payload) => sendJson(`/recommendations/${id}`, 'PUT', payload)
export const getInterventions = (params = '') => getJson(`/interventions${params}`)
export const createIntervention = (payload) => sendJson('/interventions', 'POST', payload)
export const updateIntervention = (id, payload) => sendJson(`/interventions/${id}`, 'PUT', payload)
export const getAnalyticsOverview = () => getJson('/analytics/overview')
export const getAttentionProjects = () => getJson('/analytics/attention')
export const getMapProjects = () => getJson('/gis/projects')
export const getIntegrationStatus = () => getJson('/integrations/status')
export const refreshProjectAssessment = (id) => sendJson(`/projects/${id}/predictions/refresh`, 'POST', {})
export const runProjectWhatIf = (id, changes) => sendJson(`/projects/${id}/what-if`, 'POST', changes)
export const login = (payload) => sendJson('/auth/login', 'POST', payload)
export const getAuthenticationStatus = () => getJson('/auth/status')
export const getCurrentUser = () => getJson('/auth/me')

export async function downloadProjectReport(projectId) {
  const response = await apiRequest(`/reports/projects/${projectId}`)
  return response.blob()
}
