"""initial BhoomiGuard schema

Revision ID: 7a474a39e45b
Revises:
Create Date: 2026-09-25 20:50:58.130362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a474a39e45b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('land_area_acres', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('affected_families', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('legal_disputes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('ownership_conflicts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('villages_affected', sa.Integer(), nullable=True),
    sa.Column('pending_court_cases', sa.Integer(), nullable=True),
    sa.Column('documentation_completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('missing_documents', sa.Integer(), nullable=True),
    sa.Column('compensation_completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compensation_pending_cases', sa.Integer(), nullable=True),
    sa.Column('average_compensation_delay_days', sa.Integer(), nullable=True),
    sa.Column('rehabilitation_completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resettlement_completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('affected_families_rehabilitated', sa.Integer(), nullable=True),
    sa.Column('pending_approvals', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('approval_delay_days', sa.Integer(), nullable=True),
    sa.Column('stakeholder_response_delay_days', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('days_in_current_stage', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('possession_completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('historical_delay_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('days_remaining_to_target', sa.Integer(), nullable=True),
    sa.Column('previous_stage_delay_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Active'::character varying"), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'officer'::character varying"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acquisition_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('case_status', sa.String(length=50), server_default=sa.text("'Open'::character varying"), nullable=True),
    sa.Column('compensation_status', sa.String(length=100), nullable=True),
    sa.Column('dispute_status', sa.String(length=100), nullable=True),
    sa.Column('documentation_status', sa.String(length=100), nullable=True),
    sa.Column('days_pending', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Pending'::character varying"), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delay_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('predicted_delay_days', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), server_default=sa.text("'Medium'::character varying"), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Pending'::character varying"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('factor_name', sa.String(length=255), nullable=False),
    sa.Column('impact', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_factors')
    op.drop_table('recommendations')
    op.drop_table('predictions')
    op.drop_table('interventions')
    op.drop_table('audit_logs')
    op.drop_table('alerts')
    op.drop_table('acquisition_cases')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
